---
title: MetadataValidationException class
second_title: GroupDocs.Metadata for Python via .NET API References
description: 
type: docs
url: /python-net/groupdocs.metadata.exceptions/metadatavalidationexception/
is_root: false
weight: 40
---

## MetadataValidationException class

The exception that is thrown when validation errors encountered during metadata saving.



**Inheritance:** [`MetadataValidationException`](/metadata/python-net/groupdocs.metadata.exceptions/metadatavalidationexception) → 
[`GroupDocsMetadataException`](/metadata/python-net/groupdocs.metadata.exceptions/groupdocsmetadataexception)



The MetadataValidationException type exposes the following members:

### Properties
| Property | Description |
| :- | :- |
| [errors](/metadata/python-net/groupdocs.metadata.exceptions/metadatavalidationexception/errors) | Gets an array of the validation errors that were encountered during the last metadata saving. |



### See Also
* module [`groupdocs.metadata.exceptions`](..)
* class [`GroupDocsMetadataException`](/metadata/python-net/groupdocs.metadata.exceptions/groupdocsmetadataexception)
* class [`MetadataValidationException`](/metadata/python-net/groupdocs.metadata.exceptions/metadatavalidationexception)
